export const productList = [{
    id: 1,
    title: "dell Pc",
    category: "desktop",
    price: 700,
    img: "img/desktop1.jpg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
}, {
    id: 2,
    title: "dell Pc",
    category: "desktop",
    price: 700,
    img: "img/desktop2.jpg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
}, {
    id: 3,
    title: "dell Pc",
    category: "desktop",
    price: 700,
    img: "img/desktop3.jpg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
}, {
    id: 4,
    title: "dell Pc",
    category: "desktop",
    price: 700,
    img: "img/desktop4.jpg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
}, {
    id: 5,
    title: "dell Pc",
    category: "desktop",
    price: 700,
    img: "img/desktop5.jpg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
}, {
    id: 6,
    title: "dell Pc",
    category: "laptop",
    price: 700,
    img: "img/laptop1.jpg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
}, {
    id: 7,
    title: "dell Pc",
    category: "laptop",
    price: 700,
    img: "img/laptop2.jpg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
}, {
    id: 8,
    title: "dell Pc",
    category: "laptop",
    price: 700,
    img: "img/laptop3.jpg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
}, {
    id: 9,
    title: "dell Pc",
    category: "mobile",
    price: 700,
    img: "img/mobile1.jpg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
}, {
    id: 10,
    title: "dell Pc",
    category: "mobile",
    price: 700,
    img: "img/mobile2.jpg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
}, {
    id: 11,
    title: "dell Pc",
    category: "mobile",
    price: 700,
    img: "img/mobile3.jpg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
}, {
    id: 12,
    title: "dell Pc",
    category: "mobile",
    price: 700,
    img: "img/mobile4.jpg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
}, {
    id: 13,
    title: "dell Pc",
    category: "tablet",
    price: 700,
    img: "img/tab1.jpg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
}, {
    id: 14,
    title: "dell Pc",
    category: "tablet",
    price: 700,
    img: "img/tab2.jpg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
}, {
    id: 15,
    title: "dell Pc",
    category: "tablet",
    price: 700,
    img: "img/tab3.jpg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
}, {
    id: 16,
    title: "dell Pc",
    category: "tablet",
    price: 700,
    img: "img/tab4.jpg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
}];