export const productList = [{
    id: 1,
    title: "Dell P Series Full HD",
    category: "desktop",
    price: 700,
    img: "img/desktop1.jpg",
    desc: `24 inch Screen Full HD (1080p) 1920 x 1080 resolution, IPS Panel.
    Aspect Ratio 16:9 and Contrast Ratio 1000:1`,
}, {
    id: 2,
    title: "Dell P Series LED-lit Monitor",
    category: "desktop",
    price: 689,
    img: "img/desktop2.jpg",
    desc: `Easy on the eyes: This TUVi Certified monitor has a flicker-free screen with ComfortView, a feature that reduces harmful blue light emissions.`,
}, {
    id: 3,
    title: "Lenovo NearEdgeless Monitor ",
    category: "desktop",
    price: 723,
    img: "img/desktop3.jpg",
    desc: `A nod to minimalistic and contemporary design, the 27-inch Lenovo Q27q-10 features an ultra-slim 6.9 mm build`,
}, {
    id: 4,
    title: "Samsung M5 Smart Monitor",
    category: "desktop",
    price: 695,
    img: "img/desktop4.jpg",
    desc: `Surrounding light is detected by a sensor to adjust brightness automatically with ADAPTIVE PICTURE`,
}, {
    id: 5,
    title: "Benq Photographer Monitor",
    category: "desktop",
    price: 650,
    img: "img/desktop5.jpg",
    desc: `DVI DVI-DL x1, HDMI HDMI (v1.4)x1, DisplayPort DisplayPort (v1.2) x1, USB 3.0 Hub USB Downstream x 2`,
}, {
    id: 6,
    title: "MI Notebook Intel Core",
    category: "laptop",
    price: 539,
    img: "img/laptop1.jpg",
    desc: `laptop processor: 10th gen intel core i5-10210u processor, 1.6 ghz base speed, 4.2 ghz max speed`,
}, {
    id: 7,
    title: "Lenovo IdeaPad S145",
    category: "laptop",
    price: 598,
    img: "img/laptop2.jpg",
    desc: `Processor: 10th Gen Intel Core i5-1035G1 | Speed: 1.0 GHz (Base) - 3.6 GHz (Max)`,
}, {
    id: 8,
    title: "Acer Aspire 3 core i5",
    category: "laptop",
    price: 645,
    img: "img/laptop3.jpg",
    desc: `Processor: Core i5-1135G7 Processor - up to 4.20 GHz, 4 cores, 8 threads`,
}, {
    id: 9,
    title: "Samsung Galaxy M12",
    category: "mobile",
    price: 225,
    img: "img/mobile1.jpg",
    desc: `48MP+5MP+2MP+2MP Quad camera setup- True 48MP (F 2.0) main camera + 5MP (F2.2)`,
}, {
    id: 10,
    title: "OPPO Reno5 Pro 5G",
    category: "mobile",
    price: 298,
    img: "img/mobile2.jpg",
    desc: `3D Borderless Sense Screen - AI Highlight Video (Ultra Night Video + Live HDR)`,
}, {
    id: 11,
    title: "Redmi 9A | Octa-core",
    category: "mobile",
    price: 269,
    img: "img/mobile3.jpg",
    desc: `16.58 centimeters (6.53 inch) HD+ multi-touch capacitive touchscreen with 1600 x 720 pixels resolution`,
}, {
    id: 12,
    title: "Apple iPhone 12 Pro",
    category: "mobile",
    price: 324,
    img: "img/mobile4.jpg",
    desc: `LiDAR Scanner for improved AR experiences, Night mode portraits`,
}, {
    id: 13,
    title: "Samsung Galaxy Tab A7",
    category: "tablet",
    price: 149,
    img: "img/tab1.jpg",
    desc: `his tablet has a 10.4 inch ( 26.31 cms) Immersive Display (2000 X 1200 pixels resolution ) with symetric bezel`,
}, {
    id: 14,
    title: "Lenovo Tab M10 Tablet ",
    category: "tablet",
    price: 189,
    img: "img/tab2.jpg",
    desc: `Android v9 Pie operating system with 4 x A53 @ 2.3GHz, 4 x A53 @ 1.8GHz MediaTek Helio P22T Tab processor`,
}, {
    id: 15,
    title: "Lenovo Tab M8 Tablet",
    category: "tablet",
    price: 209,
    img: "img/tab3.jpg",
    desc: `8MP rear camera with auto focus | 2MP front camera 20.32 centimeters (8-inch) `,
}, {
    id: 16,
    title: "HUAWEI MediaPad Tablet",
    category: "tablet",
    price: 188,
    img: "img/tab4.jpg",
    desc: `Dual stereo speakers – It houses dual stereo speakers with HUAWEI Histen audio technology`,
}];